### ISSUE TITLE
Remove migration entrypoints/storage

### ISSUE THREAD

**Issue by michaeljklein** [tqtezos/baseDAO#173]
# Clarification and motivation

Full migration of a DAO would require extensive migrations of the ledgers, users, proposals, etc.
This can effectively only be done "lazily", i.e. on a per-user basis, but:
- Such a lazy migration is possible without explicit migration functionality
- In this case, there's no need to lock the contract
- TreasuryDAO may transfer all funds and RegistryDAO can set registry entries to indicate migration

# Acceptance criteria

Remove the following entrypoints, along with their storage values and related functionality:
- `migrate`
- `confirm_migration`

**Comment by pasqu4le** [comment]
@michaeljklein I wonder if it's worth giving up some migration sub-features that are not mentioned in the description:

First: migration currently tracks where the contract has migrated (if any).
AFAIU with the changes proposed here there won't be any way to know what the "replacing" contract address is from the current contract `storage`.

Moreover a user currently cannot mistakenly interact with a migrating DAO because it's locked, which is especially important in case a migration just started or is still undergoing.
Related to the previous point is that it's not easy to tell from the deployed contract if it has been migrated or is in the process of doing so. 

Lastly while Treasury and Registry DAOs might be migrated as you described, that's not necessarily true for other custom DAOs, who might need to have form of locking build-in.

What do you think? Are these points valid enough to keep the migration storage/entrypoints?

**Comment by michaeljklein** [comment]
- TreasuryDAO is migrated when its balance is transferred out
  * Interacting with the DAO during or after migration is fine
- RegistryDAO is migrated when either an agreed-upon registry entry is set or the "control is transferred out"
  * Similarly, interacting with the DAO during or after migration is fine

Other DAO's may be extremely custom and so could use this feature, but we don't have any such DAO planned.

**Comment by pasqu4le** [comment]
Yeah I was thinking more of custom DAOs, but they could implement a specific migrations feature with custom entrypoints if they need to.

:ok_hand: got it
