### ISSUE TITLE
Remove unnecessary files from template/

### ISSUE THREAD

**Issue by gromakovsky** [tqtezos/baseDAO#62]
# Clarification and motivation

I think we want the `template` folder to be as small as possible, so that it doesn't look scary for newcomers who may be not quite familiar with Haskell. I think we can decrease the number of files there.

# Acceptance criteria

1. `README.md.license` is inlined into `README.md` because this template package won't go to Hackage anyway (and an extra license file doesn't look attractive to an external user).
2. `stack.yaml.lock` is removed and gitignored, it's not very useful anyway and adds extra hassle to a user not familiar with Stack.
3. `templateDAO.cabal` is probably not needed as well because this package won't be used as a library, it doesn't even have a library. And the main reason to include this file into a repo is to use it as a dependency with Stack.

**Comment by Martoon-00** [comment]
If so, the original "just copy and use" purpose seems to be not achieved anymore :thinking: 

1. Should I try to turn `Main.hs` into a Haskell stack script so that it includes shebang with stack and imports the snapshot on itself?
2. Do we now need a separate `template` folder at all? AFAIU it is going to contain only 
* `Main.hs` - could be moved to form a second executable of `baseDAO` package
* `README.md` - can be just inlined into the root `README.md`, and this makes sense since it is actually not for copy-pasting, rather it is an instruction.
* `snapshot.yaml` - imo its current location is not very canonical, probably leaving a `TODO: also copy the snapshot file` in `Main` is enough, any tech-savvy user should be able to spot an copy this file. Alternatively, we could specify a URL to our file as the stack snapshot - in this case, we should somehow ensure that on changes in snapshot this URL is updated as well.

**Comment by gromakovsky** [comment]
> If so, the original "just copy and use" purpose seems to be not achieved anymore thinking

Erm, why so? What I propose to remove is just 2 auto-generated files and 1 license file, they shouldn't affect the ability to "just copy and use".

> AFAIU it is going to contain only

You missed `package.yaml` and `stack.yaml` in this list.

> Should I try to turn `Main.hs` into a Haskell stack script so that it includes shebang with stack and imports the snapshot on itself?

Well, I guess this approach also makes sense, maybe it would be better if we did it this way instead of creating a full project. It depends on whether the users of this approach want to quickly create a small DAO or want to have an actual package.
I think currently there is not much sense in doing this change because we don't have actual users of this `template/` and it's hard to improve UX for non-existing users. So we can treat this `template/` thing as just a proof-of-concept and refine it later if it gets actual users.

The changes suggested in this PR are really trivial and simply remove some files from this repo which is usually a good thing to do anyway. So I propose to make them despite proposing not to refine this approach yet.

**Comment by Martoon-00** [comment]
Oh okay, I see now what exactly you have in mind.
