### ISSUE TITLE
Fixed Fee for All Proposals 

### ISSUE THREAD

**Issue by obstropolos** [tqtezos/baseDAO#67]
### Clarification and motivation

Have the possible requirement of having a modifiable fixed fee in either the native DAO asset or tez order to submit proposals to prevent spam. This fee being something that replaces the "proportion of the ask" style spam-measure.

**Comment by gromakovsky** [comment]
Fees in tez are in fact already possible: one may define `proposalCheck` to check `AMOUNT`. So if we want to require a proposer to spend 1 tez, we can fail in `proposalCheck` if `AMOUNT` is not equal to 1 tez.

Regarding fees in the native DAO asset, since it needs to be a fixed value, we can store this fee in the storage and subtract it from the proposer's balance when `propose` is called. What do we want to do with these fees? Burn, transfer to the admin, transfer to another dedicated address, transfer to `SELF`? Should it be complementary to the freezing mechanism, so that in some cases one may have to freeze 50 tokens (these 50 tokens will be returned afterwards) and pay 10 tokens as a fee (that will never be returned)?

**Comment by obstropolos** [comment]
Great re: tez

As for the asset, I think we can make it so that the user is returned the fee in the native asset if the proposal passes, else it's burned if it fails
