### ISSUE TITLE
Allow `flush` to accepts an amout of proposals, add `dropProposals` entrypoint

### ISSUE THREAD

**Issue by rinn7e** [tqtezos/baseDAO#69]
# Clarification and motivation
When calling `flush`, `decisionLambda` or `rejectedValue` lambda may fail due to unexpected error. We should have a way to drop some proposals and a way to not flush proposals all at one.

# Acceptance criteria
1. Allow `flush` to accepts an amount of proposals it should consume.
2. Add `dropProposals` entrypoint that will drop a number of proposals from the current ongoing proposals.

**Comment by gromakovsky** [comment]
Note that as part of this issue we should also specify the order in which proposals are executed. `flush` can execute multiple proposals and the order may matter. The tricky thing here is that we can't just say "the earliest proposal is executed first" because 2 `propose` calls can be included in the same block and have the same `NOW` timestamp.
