### ISSUE TITLE
Add a function similar to `originateBaseDaoWithBalance` that allows customize `Storage`

### ISSUE THREAD

**Issue by rinn7e** [tqtezos/baseDAO#96]
# Clarification and motivation
The function used to originate baseDao called `originateBaseDaoWithBalance` only accepts parameter that changes `Config` and ledger balance. In certain tests, we want to customize the storage value as well (e.q. `votingPeriod`, `quorumThreshold`).

# Acceptance criteria

Modify `originateBaseDaoWithBalance` or add a new function that allows originating basedao with custom storage.

**Comment by pasqu4le** [comment]
@rinn7e correct me if I'm wrong, but I think we eventually solved this already.

AFAIK when necessary in tests we parse the storage (now `FullStorage`) and then modify its content, which solves what this issue was for.

For example, the `initialStorage` in RegistryDAO's tests that [we use here](https://github.com/tqtezos/baseDAO/blob/b414e4d4e94fe83e380d791a74218f839337c96f/haskell/test/Test/Ligo/RegistryDAO.hs#L429).

Am I correct? If so, can we close this issue?

**Comment by rinn7e** [comment]
> @rinn7e correct me if I'm wrong, but I think we eventually solved this already.
> 
> AFAIK when necessary in tests we parse the storage (now `FullStorage`) and then modify its content, which solves what this issue was for.
> 
> For example, the `initialStorage` in RegistryDAO's tests that [we use here](https://github.com/tqtezos/baseDAO/blob/b414e4d4e94fe83e380d791a74218f839337c96f/haskell/test/Test/Ligo/RegistryDAO.hs#L429).
> 
> Am I correct? If so, can we close this issue?

Yeah, I think we can close this. This issue is meant to figure out a more customizable way to change the balance of the originate functions. But I'm not sure what else need to be updated and I think the currently way is good enough.
